#!/usr/bin/perl

use strict;
use warnings;

sub println {
    my ($message) = @_;
    print "$message\n";
}

sub setPower{
    my ($volt, $amp) = @_;
    return $volt * $amp;
}

my %fan= (
    "name" => "SUPERRED",
    "voltage"  => 12,
    "current"  => 0.125,
    "power"    => 12 * 0.125 
);

my %FET= (
    "name" => "2N7000",
    "V-GS(ON)"  => "2.1",
    "V-DS(ON)"  => "0.6 \@V-GS = 10V, I-D=500mA"
);

my $fan_Voltage=12;
my $fan_Current=.12;
my $fan_Power = setPower($fan_Voltage, $fan_Current);

sub getData{
    my ($f_vol, $fcurr, $f_pow) = @_;
    $fan_Power=$fan{"power"};
    print "Fan-size-details:\n";
    print "Voltage: ";
    $fan_Voltage=$fan{"voltage"};
    print "$fan_Voltage";
    $fan_Current=$fan{"current"};
    print "\nCurrent: ";
    print "$fan_Current";
    $fan_Power=$fan{"power"};
    print "\nPower: ";
    println $fan_Power;
}
&getData($fan_Voltage,$fan_Current,$fan_Power);
exit 0


#print "Name: $person{'name'}\n"; # Access a value by its key
#print "Age: $person{'age'}\n";
